name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.6
  - dask
  - numpy
  - pytest
  - future
  - zarr
  - cachetools
  - pip:
    - git+https://github.com/pydata/xarray.git
    - fsspec
    - codecov
    - pytest-cov
