name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - dask
  - numpy
  - pytest
  - future
  - zarr
  - cftime
  - aiohttp
  - pytest-cov
  - codecov
  - fsspec
  - cachetools
  - git
  - pip
  - pip:
    - git+https://github.com/pydata/xarray.git
