name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray
  - dask
  - numpy
  - pytest
  - future
  - zarr
  - cftime
  - pip:
    - cachetools
    - fsspec
    - codecov
    - pytest-cov
