name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.13
  - xarray
  - dask
  - numpy
  - pytest
  - future
  - zarr
  - cftime
  - aiohttp
  - pytest-cov
  - codecov
  - fsspec
  - cachetools
  - setuptools >=68
  - wheel
  - pip >=24
